### ISSUE TITLE
Empty file when input is same as output (replace)

### ISSUE THREAD

**Issue by softdays** [jbgraug/postbuild#3]
I would like to replace my html file instead of creating a new one but when I try to remove output option the generated file is empty

**Comment by DannyMoerkerke** [comment]
What exactly have you tried? What options?

**Comment by softdays** [comment]
For example :
postbuild -i dist/index.html -r production
postbuild -i dist.html -o dist.html -r production
Both produce an empty file without error

On Fri, Sep 09, 2016 at 10:12 AM, Danny Moerkerke < notifications@github.com [notifications@github.com] > wrote:
What exactly have you tried? What options?

**Comment by fvena** [comment]
In the last row of file postbuild:

.pipe(fs.createWriteStream(program.output,{flags: 'r+'}));

"Modifying a file rather than replacing it may require a flags mode of r+ rather than the default mode w." doc
